const suggestionPrompts = [
    "What's your secret to the perfect fried chicken?",
    "Do you have any tips for cooking the best mashed potatoes?",
    "What’s your favorite memory of starting KFC?",
    "How do you balance the 11 herbs and spices?",
    "What's the most important lesson in life you've learned?",
    "How did you perfect the art of frying chicken?",
    "What’s the key to making crispy fried chicken?",
    "Can you share your tips for making gravy?",
    "What’s the secret behind your buttermilk biscuits?",
    "How do you stay motivated in tough times?",
    "What advice do you have for aspiring chefs?",
    "What's your favorite side dish to pair with fried chicken?",
    "Do you have any secret recipes for holiday meals?",
    "What keeps your fried chicken so juicy on the inside?",
    "What role did persistence play in your success?",
    "How did you come up with the idea for KFC?",
    "What's your opinion on fast food today?",
    "What’s your go-to comfort food when you're not cooking?",
    "How can home cooks improve their fried chicken?",
    "What’s the most satisfying part of running a business?",
    "Do you have any tips for perfecting coleslaw?",
    "How do you manage to make gravy so flavorful?",
    "What's your recipe for the perfect mashed potatoes?",
    "What’s your favorite memory from running your restaurant?",
    "What's the biggest challenge you faced in business?",
    "How can you tell when fried chicken is cooked just right?",
    "What makes a great meal beyond just the food?",
    "How do you feel about competition like McDonald's?",
    "What inspires you to keep innovating in the kitchen?",
    "Do you have a favorite international dish?",
    "What's your advice for balancing work and life?",
    "How do you season your chicken for that perfect flavor?",
    "What’s the key to making chicken wings taste great?",
    "Can you tell us a story about your early cooking days?",
    "What’s the best way to fry chicken without a deep fryer?",
    "How can I make healthier versions of your famous dishes?"
  ];
  
  export default suggestionPrompts;
  